<?php

/**
 * This configuration cache file was generated by Laminas\ConfigAggregator\ConfigAggregator
 * at 2025-07-14T21:59:25+00:00
 */
return [
    'dependencies' => [
        'invokables' => [
            'Mezzio\\Helper\\ServerUrlHelper' => 'Mezzio\\Helper\\ServerUrlHelper',
            'Mezzio\\Helper\\Template\\TemplateVariableContainerMiddleware' => 'Mezzio\\Helper\\Template\\TemplateVariableContainerMiddleware',
            'Psr\\Http\\Message\\RequestFactoryInterface' => 'Laminas\\Diactoros\\RequestFactory',
            'Psr\\Http\\Message\\ResponseFactoryInterface' => 'Laminas\\Diactoros\\ResponseFactory',
            'Psr\\Http\\Message\\StreamFactoryInterface' => 'Laminas\\Diactoros\\StreamFactory',
            'Psr\\Http\\Message\\ServerRequestFactoryInterface' => 'Laminas\\Diactoros\\ServerRequestFactory',
            'Psr\\Http\\Message\\UploadedFileFactoryInterface' => 'Laminas\\Diactoros\\UploadedFileFactory',
            'Psr\\Http\\Message\\UriFactoryInterface' => 'Laminas\\Diactoros\\UriFactory'
        ],
        'factories' => [
            'Mezzio\\Helper\\ServerUrlMiddleware' => 'Mezzio\\Helper\\ServerUrlMiddlewareFactory',
            'Mezzio\\Helper\\UrlHelper' => 'Mezzio\\Helper\\UrlHelperFactory',
            'Mezzio\\Helper\\UrlHelperMiddleware' => 'Mezzio\\Helper\\UrlHelperMiddlewareFactory',
            'Laminas\\Validator\\ValidatorChainFactory' => 'Laminas\\Validator\\ValidatorChainFactoryFactory',
            'Laminas\\Validator\\ValidatorPluginManager' => 'Laminas\\Validator\\ValidatorPluginManagerFactory',
            'Laminas\\ServiceManager\\Tool\\ConfigDumperInterface' => 'Laminas\\ServiceManager\\Tool\\ConfigDumperFactory',
            'Laminas\\ServiceManager\\Tool\\FactoryCreatorInterface' => 'Laminas\\ServiceManager\\Tool\\FactoryCreatorFactory',
            'Laminas\\ServiceManager\\Tool\\AheadOfTimeFactoryCompiler\\AheadOfTimeFactoryCompilerInterface' => 'Laminas\\ServiceManager\\Tool\\AheadOfTimeFactoryCompiler\\AheadOfTimeFactoryCompilerFactory',
            'Laminas\\ServiceManager\\Tool\\ConstructorParameterResolver\\ConstructorParameterResolverInterface' => function (): \Laminas\ServiceManager\Tool\ConstructorParameterResolver\ConstructorParameterResolverInterface {
                return new \Laminas\ServiceManager\Tool\ConstructorParameterResolver\ConstructorParameterResolver();
            },
            'Laminas\\ServiceManager\\Command\\AheadOfTimeFactoryCreatorCommand' => 'Laminas\\ServiceManager\\Command\\AheadOfTimeFactoryCreatorCommandFactory',
            'Laminas\\ServiceManager\\Command\\ConfigDumperCommand' => 'Laminas\\ServiceManager\\Command\\ConfigDumperCommandFactory',
            'Laminas\\ServiceManager\\Command\\FactoryCreatorCommand' => 'Laminas\\ServiceManager\\Command\\FactoryCreatorCommandFactory',
            'Mezzio\\Application' => 'Mezzio\\Container\\ApplicationFactory',
            'Mezzio\\ApplicationPipeline' => 'Mezzio\\Container\\ApplicationPipelineFactory',
            'Laminas\\HttpHandlerRunner\\Emitter\\EmitterInterface' => 'Mezzio\\Container\\EmitterFactory',
            'Laminas\\Stratigility\\Middleware\\ErrorHandler' => 'Mezzio\\Container\\ErrorHandlerFactory',
            'Mezzio\\Handler\\NotFoundHandler' => 'Mezzio\\Container\\NotFoundHandlerFactory',
            'Mezzio\\MiddlewareContainer' => 'Mezzio\\Container\\MiddlewareContainerFactory',
            'Mezzio\\MiddlewareFactory' => 'Mezzio\\Container\\MiddlewareFactoryFactory',
            'Mezzio\\Middleware\\ErrorResponseGenerator' => 'Mezzio\\Container\\ErrorResponseGeneratorFactory',
            'Laminas\\HttpHandlerRunner\\RequestHandlerRunner' => 'Mezzio\\Container\\RequestHandlerRunnerFactory',
            'Psr\\Http\\Message\\ResponseInterface' => 'Mezzio\\Container\\ResponseFactoryFactory',
            'Mezzio\\Response\\ServerRequestErrorResponseGenerator' => 'Mezzio\\Container\\ServerRequestErrorResponseGeneratorFactory',
            'Psr\\Http\\Message\\ServerRequestInterface' => 'Mezzio\\Container\\ServerRequestFactoryFactory',
            'Psr\\Http\\Message\\StreamInterface' => 'Mezzio\\Container\\StreamFactoryFactory',
            'Mezzio\\Router\\Middleware\\DispatchMiddleware' => 'Mezzio\\Router\\Middleware\\DispatchMiddlewareFactory',
            'Mezzio\\Router\\Middleware\\ImplicitHeadMiddleware' => 'Mezzio\\Router\\Middleware\\ImplicitHeadMiddlewareFactory',
            'Mezzio\\Router\\Middleware\\ImplicitOptionsMiddleware' => 'Mezzio\\Router\\Middleware\\ImplicitOptionsMiddlewareFactory',
            'Mezzio\\Router\\Middleware\\MethodNotAllowedMiddleware' => 'Mezzio\\Router\\Middleware\\MethodNotAllowedMiddlewareFactory',
            'Mezzio\\Router\\Middleware\\RouteMiddleware' => 'Mezzio\\Router\\Middleware\\RouteMiddlewareFactory',
            'Mezzio\\Router\\RouteCollector' => 'Mezzio\\Router\\RouteCollectorFactory',
            'Mezzio\\Router\\FastRouteRouter' => 'Mezzio\\Router\\FastRouteRouterFactory',
            'Light\\Core\\Service\\TemplatePathProviderInterface' => 'Light\\Core\\Factory\\TemplatePathProviderFactory',
            'Mezzio\\Template\\TemplateRendererInterface' => 'Light\\Core\\Factory\\NativePhpRendererFactory',
            'Dot\\ErrorHandler\\LogErrorHandler' => 'Dot\\ErrorHandler\\LogErrorHandlerFactory',
            'Dot\\ErrorHandler\\ErrorHandler' => 'Dot\\ErrorHandler\\ErrorHandlerFactory',
            'Dot\\Log\\Logger' => 'Dot\\Log\\LoggerServiceFactory',
            'LogFilterManager' => 'Dot\\Log\\Factory\\FilterPluginManagerFactory',
            'LogFormatterManager' => 'Dot\\Log\\Factory\\FormatterPluginManagerFactory',
            'LogProcessorManager' => 'Dot\\Log\\Factory\\ProcessorPluginManagerFactory',
            'LogWriterManager' => 'Dot\\Log\\Factory\\WriterPluginManagerFactory',
            'Light\\App\\Handler\\GetIndexViewHandler' => 'Light\\App\\Factory\\GetIndexViewHandlerFactory',
            'Light\\App\\Handler\\PathsExampleHandler' => 'Light\\App\\Factory\\PathsExampleHandlerFactory',
            'ResponsiveSk\\Slim4Paths\\Paths' => 'Light\\App\\Factory\\PathsFactory',
            'Light\\Page\\Handler\\GetPageViewHandler' => 'Light\\Page\\Factory\\GetPageViewHandlerFactory',
            'Light\\Page\\Service\\PageService' => 'Light\\Page\\Factory\\PageServiceFactory',
            'Twig\\Environment' => 'Light\\Core\\Factory\\PathsAwareTwigEnvironmentFactory'
        ],
        'aliases' => [
            'Mezzio\\Helper\\UrlHelperInterface' => 'Mezzio\\Helper\\UrlHelper',
            'ValidatorManager' => 'Laminas\\Validator\\ValidatorPluginManager',
            'Mezzio\\Delegate\\DefaultDelegate' => 'Mezzio\\Handler\\NotFoundHandler',
            'Mezzio\\Middleware\\DispatchMiddleware' => 'Mezzio\\Router\\Middleware\\DispatchMiddleware',
            'Mezzio\\Middleware\\ImplicitHeadMiddleware' => 'Mezzio\\Router\\Middleware\\ImplicitHeadMiddleware',
            'Mezzio\\Middleware\\ImplicitOptionsMiddleware' => 'Mezzio\\Router\\Middleware\\ImplicitOptionsMiddleware',
            'Mezzio\\Middleware\\NotFoundMiddleware' => 'Mezzio\\Handler\\NotFoundHandler',
            'Mezzio\\Middleware\\RouteMiddleware' => 'Mezzio\\Router\\Middleware\\RouteMiddleware',
            'Laminas\\HttpHandlerRunner\\RequestHandlerRunnerInterface' => 'Laminas\\HttpHandlerRunner\\RequestHandlerRunner',
            'Mezzio\\MiddlewareFactoryInterface' => 'Mezzio\\MiddlewareFactory',
            'Zend\\Expressive\\Application' => 'Mezzio\\Application',
            'Zend\\Expressive\\ApplicationPipeline' => 'Mezzio\\ApplicationPipeline',
            'Zend\\HttpHandlerRunner\\Emitter\\EmitterInterface' => 'Laminas\\HttpHandlerRunner\\Emitter\\EmitterInterface',
            'Zend\\Stratigility\\Middleware\\ErrorHandler' => 'Laminas\\Stratigility\\Middleware\\ErrorHandler',
            'Zend\\Expressive\\Handler\\NotFoundHandler' => 'Mezzio\\Handler\\NotFoundHandler',
            'Zend\\Expressive\\MiddlewareContainer' => 'Mezzio\\MiddlewareContainer',
            'Zend\\Expressive\\MiddlewareFactory' => 'Mezzio\\MiddlewareFactory',
            'Zend\\Expressive\\Middleware\\ErrorResponseGenerator' => 'Mezzio\\Middleware\\ErrorResponseGenerator',
            'Zend\\HttpHandlerRunner\\RequestHandlerRunner' => 'Laminas\\HttpHandlerRunner\\RequestHandlerRunner',
            'Zend\\Expressive\\Response\\ServerRequestErrorResponseGenerator' => 'Mezzio\\Response\\ServerRequestErrorResponseGenerator',
            'Mezzio\\Router\\RouteCollectorInterface' => 'Mezzio\\Router\\RouteCollector',
            'Mezzio\\Router\\RouterInterface' => 'Mezzio\\Router\\FastRouteRouter',
            'Zend\\Expressive\\Router\\RouterInterface' => 'Mezzio\\Router\\RouterInterface',
            'Zend\\Expressive\\Router\\FastRouteRouter\\FastRouteRouter' => 'Mezzio\\Router\\FastRouteRouter',
            'Dot\\ErrorHandler\\ErrorHandlerInterface' => 'Dot\\ErrorHandler\\LogErrorHandler',
            'Dot\\Log\\Manager\\FilterPluginManager' => 'LogFilterManager',
            'Dot\\Log\\Manager\\FormatterPluginManager' => 'LogFormatterManager',
            'Dot\\Log\\Manager\\ProcessorPluginManager' => 'LogProcessorManager',
            'Dot\\Log\\Manager\\WriterPluginManager' => 'LogWriterManager',
            'Light\\Page\\Service\\PageServiceInterface' => 'Light\\Page\\Service\\PageService'
        ],
        'abstract_factories' => [
            'Dot\\Log\\Factory\\LoggerAbstractServiceFactory'
        ],
        'delegators' => [
            'Mezzio\\Application' => [
                'Light\\App\\RoutesDelegator',
                'Light\\Page\\RoutesDelegator'
            ]
        ]
    ],
    'laminas-cli' => [
        'commands' => [
            'servicemanager:generate-deps-for-config-factory' => 'Laminas\\ServiceManager\\Command\\ConfigDumperCommand',
            'servicemanager:generate-factory-for-class' => 'Laminas\\ServiceManager\\Command\\FactoryCreatorCommand',
            'servicemanager:generate-aot-factories' => 'Laminas\\ServiceManager\\Command\\AheadOfTimeFactoryCreatorCommand'
        ]
    ],
    'config_cache_path' => 'var/cache/config-cache.php',
    'laminas-diactoros' => [
        'x-forwarded-request-filter' => [
            'trusted-proxies' => '',
            'trusted-headers' => []
        ]
    ],
    'dot_log' => [
        'formatter_manager' => [],
        'filter_manager' => [],
        'processor_manager' => [],
        'writer_manager' => [],
        'loggers' => [
            'default_logger' => [
                'writers' => [
                    'FileWriter' => [
                        'name' => 'stream',
                        'level' => 1,
                        'options' => [
                            'stream' => '/home/dan/Desktop/07/dk/light/config/autoload/../../var/logs/error-log-{Y}-{m}-{d}.log',
                            'filters' => [
                                'allMessages' => [
                                    'name' => 'level',
                                    'options' => [
                                        'operator' => '>=',
                                        'level' => 0
                                    ]
                                ]
                            ],
                            'formatter' => [
                                'name' => 'Dot\\Log\\Formatter\\Json'
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ],
    'templates' => [
        'paths' => [],
        'extension' => 'html.twig'
    ],
    'app' => [
        'name' => 'Dotkernel Light | PSR-15 compliant application'
    ],
    'dot-errorhandler' => [
        'loggerEnabled' => true,
        'logger' => 'dot-log.default_logger',
        'extraProvider' => [
            'Dot\\ErrorHandler\\Extra\\Provider\\CookieProvider' => [
                'enabled' => false
            ],
            'Dot\\ErrorHandler\\Extra\\Provider\\HeaderProvider' => [
                'enabled' => false
            ],
            'Dot\\ErrorHandler\\Extra\\Provider\\RequestProvider' => [
                'enabled' => false
            ],
            'Dot\\ErrorHandler\\Extra\\Provider\\ServerProvider' => [
                'enabled' => true
            ],
            'Dot\\ErrorHandler\\Extra\\Provider\\SessionProvider' => [
                'enabled' => false
            ],
            'Dot\\ErrorHandler\\Extra\\Provider\\TraceProvider' => [
                'enabled' => true
            ]
        ]
    ],
    'config_cache_enabled' => true,
    'debug' => false,
    'mezzio' => [
        'error_handler' => [
            'template_404' => 'error::404',
            'template_error' => 'error::error'
        ]
    ],
    'paths' => [
        'base_path' => '/home/dan/Desktop/07/dk/light',
        'preset' => 'mezzio',
        'custom_paths' => [
            'data' => 'var/data',
            'log' => 'var/logs',
            'logs' => 'var/logs',
            'cache' => 'var/cache',
            'tmp' => 'var/tmp'
        ],
        'templates' => [
            'app' => 'src/App/templates/app',
            'error' => 'src/App/templates/error',
            'layout' => 'src/App/templates/layout',
            'partial' => 'src/App/templates/partial',
            'page' => 'src/Page/templates/page'
        ],
        'cache' => [
            'config' => 'var/cache/config',
            'twig' => 'var/cache/twig',
            'routes' => 'var/cache/routes'
        ],
        'assets' => [
            'css' => 'public/css',
            'js' => 'public/js',
            'images' => 'public/images',
            'fonts' => 'public/fonts'
        ],
        'modules' => [
            'user' => 'modules/User',
            'mark' => 'modules/Mark',
            'blog' => 'modules/Blog'
        ],
        'custom' => [
            'uploads' => 'public/uploads',
            'downloads' => 'public/downloads',
            'temp' => 'var/tmp',
            'sessions' => 'var/sessions',
            'logs' => 'var/logs',
            'tests' => 'test',
            'docs' => 'docs',
            'bin' => 'bin'
        ],
        'security' => [
            'enable_path_traversal_protection' => true,
            'enable_encoding_protection' => true,
            'enable_length_validation' => true,
            'max_path_length' => 4096,
            'max_filename_length' => 255,
            'trusted_paths' => []
        ],
        'framework_preset' => 'mezzio'
    ],
    'twig' => [
        'assets_url' => '/',
        'assets_version' => null,
        'autoescape' => 'html',
        'auto_reload' => false,
        'cache_dir' => 'var/cache/twig',
        'extensions' => [],
        'globals' => [],
        'optimizations' => -1,
        'runtime_loaders' => [],
        'timezone' => 'UTC',
        'debug' => false,
        'strict_variables' => false,
        'options' => [
            'charset' => 'UTF-8',
            'optimizations' => -1
        ]
    ],
    'application' => [
        'url' => 'http://light.dotkernel.localhost'
    ],
    'routes' => [
        'page' => [
            'about' => 'about',
            'who-we-are' => 'who-we-are'
        ]
    ]
];

